### ISSUE TITLE
Documented Interact Examples

### ISSUE THREAD

**Issue by kramer314** [sagemath/sagecell#115]
As we're adding some new features to interacts as well as trying to maintain previous sage functionality, we should create a basic library of interacts (that could also serve as a 'test suite') demonstrating our version of interacts to provide another way for users who haven't actively worked on the project or aren't incredibly familiar with the documentation have something they can easily refer back to for examples.

This also provides an opportunity to come up with fun, interesting, and potentially-complex interacts.

**Comment by novoselt** [comment]
The plan is to have no new features, but rather be the same as other interfaces with exactly the same documentation!
