### ISSUE TITLE
provide convenience script which kills workers after a certain walltime

### ISSUE THREAD

**Issue by jasongrout** [sagemath/sagecell#120]
Sometimes workers will hang, despite having resource limits and other things.  An _outside_ script that kills things that have been alive for too long (wall-time) would be nice.  It could run in a cronjob.

**Comment by novoselt** [comment]
This does not seem a problem anymore after dda0fede9d3999fc37e89802355a169536ced96f
A possible reason for "hanged" kernels was using the same ZMQ sockets from different threads leading to lost messages about killing kernels. We'll probably never know for sure ;-)
