### ISSUE TITLE
javascript dynamic loading tags should be appended to the embedded_cell script tag

### ISSUE THREAD

**Issue by jasongrout** [sagemath/sagecell#281]
Currently, when dynamically loading our javascript modules, we append the script tags to the head.  However, we really should insert them just after the script tag that loads the embedded_sagecell.js.  Otherwise the timing of loading things is thrown off.  It seems like I've seen problems from this at least once.

I have some code to do this at my https://github.com/jasongrout/sagecell/tree/append-after-current-script branch, but it's not currently working, IIRC.

**Comment by novoselt** [comment]
It seems that "the best practice" is to insert dynamic scripts in the beginning, I've done it in bec29d290408064a1b71acbd62dde01b3e14d07b
