### ISSUE TITLE
Sage Patches cause html function not to work in the Notebook

### ISSUE THREAD

**Issue by ihanson** [sagemath/sagecell#364]
After applying the Sage Cell patches to Sage 5.3, the `html` and `html.table` functions produce output in the Sage Cell, but not the Notebook. If
```python
misc.EMBEDDED_MODE["frontend"] = "notebook"
```
is set in the Notebook before calling `html`, it will work.

**Comment by kcrisman** [comment]
Just FYI, and presumably related to this, I can't get `html(table(list of lists))` to work in Sage cell server.  However, `html.table(list of lists)` still works (phew).

**Comment by novoselt** [comment]
I hope (and probably will be forced) to rewrite output tweaking of SageCell once http://trac.sagemath.org/ticket/17234 is in Sage. It is indeed extremely annoying to have inconsistent behaviour between SageNB/SageCell/SMC/command line as it prevents one from copy-pasting etc.

**Comment by kcrisman** [comment]
> It is indeed extremely annoying to have inconsistent behaviour between SageNB/SageCell/SMC/command line as it prevents one from copy-pasting etc.

Agreed!  I can at least help with testing, though not writing, as I don't understand Sage cell at all.

**Comment by novoselt** [comment]
This should not be relevant anymore as SageMathCell uses its own display backend and the plan is to eventually not apply any patches.
