### ISSUE TITLE
interact library uses old interact version

### ISSUE THREAD

**Issue by jasongrout** [sagemath/sagecell#385]
From @williamstein:

I tried the "library interacts" in http://aleph.sagemath.org and all
the ones I tried don't work at all.   E.g.,

interacts.calculus.definite_integral()

in aleph just shows a big html string.

My reply:

Thanks for pointing this out.  It's probably because the builtin interact library imports the builtin interact files, which are not the interact files we use.  We override the interact function for the user, but we (currently) don't patch the Sage library to fix the references to interact there.

**Comment by novoselt** [comment]
Works fine now (not sure for how long and what exactly has fixed the problem, most likely something in SageMath itself).
