### ISSUE TITLE
Error message handling

### ISSUE THREAD

**Issue by sdenton4** [sagemath/sagecell#401]
Currently, Sage error messages lead the Python client to hang indefinitely and an unending 'busy' signal in the in-browser sage-cell.  (I've been playing with the python client a lot more than the javascript client, so the following concerns just the python client.)  The problem seems to be twofold:

Easy: The iopub channel finishes with a message with 'dead' 'execution_state'.  This isn't covered by the current checks, but is trivial to fix.

Seemingly harder: In case of an error, the shell channel doesn't send any messages at all.  This causes an infinite hang, seemingly at the command:
msg = json.loads(self._shell.recv())
which I think is expecting _something_ to come down the pipe eventually.

Two possible ways to fix this would be some kind of a timeout on the threads, and/or making sure that the shell sends something along in case of an error message on iopub.  Some sort of robustness in case of lost/garbled messages also seems good, so a timeout or something would maybe be the preferable solution.
@gissues:{"order":50,"status":"inprogress"}

**Comment by novoselt** [comment]
As there are no more complaints and sagecell-client is not using threads anymore, I'll assume that this is fixed.
