### ISSUE TITLE
graphics with NaN throw a json error

### ISSUE THREAD

**Issue by jasongrout** [sagemath/sagecell#433]
This is because json doesn't actually support NaN:

https://github.com/ipython/ipython/issues/2187/

http://stackoverflow.com/questions/6601812/sending-nan-in-json

We could clean the NaN out of the json, we could throw an error by setting allow_nan to false, or we could just use the IPython json cleaning function.

**Comment by novoselt** [comment]
The plan is to fix it for threejs in Sage itself, https://trac.sagemath.org/ticket/22688
