### ISSUE TITLE
all sage output not shown in result box

### ISSUE THREAD

**Issue by rwst** [sagemath/sagecell#436]
Input A:

```
print 1
print 2
```

Output A:

```
1
2
```

Input B:

```
1
2
```

Output B:

```
2
```

This is completely unexpected and inexplainable and therefore a blocker to me.

**Comment by novoselt** [comment]
I stick to "this is the design" opinion - if underlying components will change the behaviour, we'll automatically change as well, otherwise there is no reason to do it and potentially break existing code.
