### ISSUE TITLE
Full-screen button not accessible after scroll is active

### ISSUE THREAD

**Issue by gurshabad** [sagemath/sagecell#439]
When in normal (not full-screen mode) mode, the full-screen button cannot be clicked if the scroll on the text box becomes active. I think the scroll bar automatically gets a higher "z-index" than the button.
A simple fix would be to move the button further left to avoid any overlap with the scroll bar but this still wouldn't fix the general issue that the button becomes a little difficult to use with the textbox.

Windows, Chrome - NOT accessible
Windows, IE - Accessible
OSX, Chrome - NOT accessible
OSX, Safari - NOT accessible

Keeping this and issue #438 in mind, I think the whole full screen functionality code will have to be looked into and some important CSS fixes made.

**Comment by novoselt** [comment]
Fixed by 187d283514c0cba16e0b757a57824b91d33c6c6c
