### ISSUE TITLE
problem with Tachyon.show() at aleph/sagecell

### ISSUE THREAD

**Issue by aghu** [sagemath/sagecell#444]
Hi sagecell community!

Recently I've tried the following code at sagecell ([permalink here]( http://sagecell.sagemath.org/?z=eJylkMsOgyAQRfdN-g-zE5MJGR9ddMFfdN9QOlYTLQYx1b8vpDX2sTRsmDlwLowHBSdt6tnexeR4UCURzssGjO7Y6bPhu2enRI6ElKb7nZdtc6u9ECUWmKcIJHMEkWFYL-558qNjkfg8QdDdpQkORTJDuDZVNQ4ciiPC0LMZW-1CdUCwvTaNn1UmY7htbQjN1tBVWmyUUnjpn7TcLKXl-0Nfc3DGVjhNy4TiNL55pJ-8SH7vR8PKyzev7UOkT6E7fF4=&lang=sage))

```sage
    t = Tachyon(xres=400,yres=400, camera_center=(2,0,0))
    t.light((4,3,2), 0.2, (1,1,1))
    t.texture('t2', ambient=0.1, diffuse=0.9, specular=0.5, opacity=1.0, color=(1,0,0))
    t.texture('t3', ambient=0.1, diffuse=0.9, specular=0.5, opacity=1.0, color=(0,1,0))
    t.texture('t4', ambient=0.1, diffuse=0.9, specular=0.5, opacity=1.0, color=(0,0,1))
    t.sphere((0,0.5,0), 0.2, 't2')
    t.sphere((0.5,0,0), 0.2, 't3')
    t.sphere((0,0,0.5), 0.2, 't4')
    t.show()
```
And this was the result:

    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-1-d6c906df5871> in <module>()
          7 t.sphere((RealNumber('0.5'),Integer(0),Integer(0)), RealNumber('0.2'), 't3')
          8 t.sphere((Integer(0),Integer(0),RealNumber('0.5')), RealNumber('0.2'), 't4')
    ----> 9 t.show()
    
    /home/sageserver/sage/local/lib/python2.7/site-packages/sage/plot/plot3d /tachyon.pyc in show(self, verbose, extra_opts)
        320             filename = graphics_filename()
        321             self.save(filename, verbose=verbose, extra_opts=extra_opts)
    --> 322             sage.misc.misc.display_image(filename)
        323             return
        324         filename = tmp_filename(ext='.png')

    AttributeError: 'module' object has no attribute 'display_image'

Same code works fine at www.sagenb.org: it shows the three spheres

I've searched sage-support, ask sage, trac sage and here in GitHub but couldn't find any similar issue.

Checking the source code I coded the following **workaround** within the cell ([permalink](http://aleph.sagemath.org/?z=eJylkcluxCAMhu-V-g7cQiQLkaWHHniL3iOXcRKkLAhINXn7Go1QuhxHHMD-7c_YTsKID7TzuW_yHiiaXms4y0NYXCngYGlLFIxsQYOu69eXpBY3zUnKHjpoaxBatSBkA3weeqJ7OgLJKrUVCFw_HTOMVg2ImxvHIxIb7yCiJ3ssGNh6A7F7tC6dplG5-L7sXLS5il7Q7kmo5p_-g_ZPQ3VpP_qZmJldHK3LhPI0futZ_al31d_8TLj0PuujW2jj1fDyIk6kVhct97H6PWA4hyyrKaCfnY1DCZYPMH6RLC72XPk3F_2CZ7kHt7J0hX4DouKkKQ==&lang=sage)):

```sage
    # t is as above
    # t.show() replaced by:
    filename = sage.misc.temporary_file.graphics_filename()
    t.save(filename)
    sage.misc.display.display_image(filename)
```

Following the track trace, I typed in the following in the cell and press tab:
```sage
    sage.plot.plot3d.tachyon??
```
Then I checked the show() method...
```sage
    def show(self, verbose=0, extra_opts=''):
    # ... ommitted ...
    if sage.misc.display.is_registered('image'):
                filename = graphics_filename()
                self.save(filename, verbose=verbose, extra_opts=extra_opts)
                sage.misc.misc.display_image(filename)
                return
```

... and I found that  `sage.misc.display.is_registered()` curious. Then I also used tab for...

```sage
    sage.misc.display.
```
... and there I found the function `display_image()`. Then I guessed that `sage.misc.misc.display_image(filename)` had mistaken the second "`misc`" . From there, I figured out the mentioned workaround.

I hope this report will become useful.

-- aghu

_PS: For reference, I first reported this at sage-support [here](https://groups.google.com/forum/#!topic/sage-support/GgZJPm94kyQ)_
_I didn't know how to write this report, so I've written it mail-like._
_Corrections and suggestions are welcomed_
_My thanks to kcrisman who point me this issue tracker, here in GitHub._

**Comment by novoselt** [comment]
Seems to work now!
