### ISSUE TITLE
Matrix input in interacts does not work

### ISSUE THREAD

**Issue by kcrisman** [sagemath/sagecell#450]
E.g. http://aleph.sagemath.org/?z=eJxzyMwrSS1KTC7h5UpJTVOI10gsLcmPLy1ISSxJtXVLzClO1XG0zU0sKcqs0AhycdOJjjbUMYjViTbQMYyN1dS04uVSAAJHLUcAjr8V9w==&lang=sage

    @interact
    def _(auto_update=False,A=matrix(RDF,[[1,0],[0,1]])):
        A*A

This is a pretty serious regression.  When did this stop working, I wonder?  It works fine in the sagenb and cloud.

**Comment by novoselt** [comment]
It is a miracle, but the original interact now seems to work as in it does not cause an error and I can even show the matix.

**Comment by kcrisman** [comment]
Yay!
