### ISSUE TITLE
Intstallation on Ubuntu Server 14.04.1 does not work: [static/require/build/widgets.js] Error 1

### ISSUE THREAD

**Issue by korniichuk** [sagemath/sagecell#459]
Hi all,

after new version of simple installation does not work installation on Ubuntu Server 14.04.1:

```
make: *** [static/require/build/widgets.js] Error 1
```

Terminal screenshot here: https://goo.gl/wZQn95

**Comment by novoselt** [comment]
Did everything else went OK? In particular replacement of IPython with a sagecell branch?

**Comment by korniichuk** [comment]
**It is work good after system was updated**. Unfortunately, we do not know what has happened.
In case of having the same use the SageMathCell installer:
https://github.com/korniichuk/sagecell
