### ISSUE TITLE
Archived page at archive.org with embedded cells

### ISSUE THREAD

**Issue by paulmasson** [sagemath/sagecell#461]
When trying to view an archived page at archive.org that has embedded cells, that website automatically tries to archive a page of the form

https://sagecell.sagemath.org/sagecell.html?rand=0.7502654224976789

Here's an example [link](http://web.archive.org/web/20160407234817/http://analyticphysics.com/Quantum%20Mechanics/Visualizing%20Continuity%20in%20Quantum%20Mechanics.htm) to illustrate what happens. The automatic archive can be halted by hitting the escape key before processing of the page begins.

Is this something that can fixed on the Sage cell server end, or is it an issue for archive.org?

**Comment by paulmasson** [comment]
The reported behavior is no longer occurring.

**Comment by novoselt** [comment]
For the record there were no changes in deployed code whatsoever. Although system libraries/dependencies may have been updated.

**Comment by paulmasson** [comment]
Dunno. Maybe it was on their end. If I see it again I'll reopen this issue.
