### ISSUE TITLE
Links on default landing page need updating

### ISSUE THREAD

**Issue by paulmasson** [sagemath/sagecell#462]
The default page in this location

http://www.sagemath.org/sagecell/

contains links that are out of date. Someone with access to the document might want to update it or redirect to an active page.

**Comment by novoselt** [comment]
On a related note - how do you land on that page? I am not sure it should exist at all and would rather it redirect to sagecell.sagemath.org with the default computational page or to github repository with installation instructions.

**Comment by paulmasson** [comment]
Redirected from sagemath.github.io/sagecell

**Comment by paulmasson** [comment]
The default page also turns up prominently when Googling "sagecell documentation".

Tried looking for it in the website repository but no luck. Maybe @haraldschilly knows where it lives.

**Comment by haraldschilly** [comment]
We have a full domain site at github via github pages. I have no idea who did create that page and why this link even exists. Does it appear somewhere else?

The page itself is here, in that gh-pages branch: https://github.com/sagemath/sagecell/tree/gh-pages

**Comment by paulmasson** [comment]
I've added a pull request #465 to redirect this location to sagecell.sagemath.org

**Comment by novoselt** [comment]
This is mighty confusing to kind of have another repository with the same name and with pull requests appearing in the main one, but commits not showing up. Anyway, redirection works now, thanks for taking care of it!

**Comment by paulmasson** [comment]
Since the commits are in the pull request I thought that would be sufficient. I'll try to remember to reference issues when creating commits in the future.

**Comment by novoselt** [comment]
Oh, I have no problems with what you have done - I am confused by gihub itself showing a pull request for sagemath/sagecell while in fact it was for the secret repository of associated web pages.
