### ISSUE TITLE
IE11 does not evaluate

### ISSUE THREAD

**Issue by novoselt** [sagemath/sagecell#466]
There is some problem with `Promise` not defined in `this._msg_queue = Promise.resolve();` here:
https://github.com/jupyter/notebook/blob/master/notebook/static/services/kernels/kernel.js#L44

The error happens when some code is entered and "Evaluate" button is pressed.

**Comment by jasongrout** [comment]
IE doesn't support promises (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#Browser_compatibility). In Jupyter, we use the es6-promise polyfill library to cover for this: https://github.com/jupyter/notebook/blob/cff1baf6f3918377b14edad7248e3447f6f41500/notebook/templates/page.html#L18, https://github.com/jupyter/jupyterlab/blob/f87ca78a967f463587919ba744d4fe4dd8d397fb/jupyterlab/index.js#L6

The library is at https://www.npmjs.com/package/es6-promise

**Comment by jasongrout** [comment]
(I added an issue to document this at https://github.com/jupyter/jupyter-js-services/issues/163,

**Comment by novoselt** [comment]
Fixed by e4a0f02fce5e7fbcfeedc5a2ceb1b0ed622116ce
