### ISSUE TITLE
latex_name and _print_latex_ not rendering for elliptic integrals

### ISSUE THREAD

**Issue by paulmasson** [sagemath/sagecell#468]
Evaluating `show(elliptic_f(z,m))` in the current cell configuration returns elliptic<sub>f</sub>(z,m) as if the function name itself were LaTeX. Existing LaTeX formatting is being ignored.

**Comment by novoselt** [comment]
Looks like Sage 7.3.beta4 which is currently running just has this LaTeX representation for this function. As it is fixed in beta8, the next upgrade will solve this issue.

**Comment by paulmasson** [comment]
While it may be solved in a upgrade, it's not because the LaTeX strings for elliptic integrals were changed: they've been the same for at least two years. There's something else going on, because Bessel functions render and elliptic integrals don't.

If you're closing the issue, are you planning to upgrade to 7.3.beta8?

**Comment by novoselt** [comment]
Something may have changed in the way symbolic expressions are rendered. SageMathCell relies on whatever latex/html methods return for Sage objects, so this issue has to be internal to Sage.

I'd rather not upgrade to another beta just for this, especially since 7.3 should be close, but in any case this is not an issue for this repository. Upgrade in Sage version happens automatically when I upgrade Sage branch in my account.

**Comment by rwst** [comment]
Well, in version 7.1, Release Date: 2016-03-20 I get
```
sage: show(elliptic_f(x,x))
\newcommand{\Bold}[1]{\mathbf{#1}}{\rm elliptic}_{f}\left(x, x\right)
```
and in 7.3.beta8, Release Date: 2016-07-14:
```
sage: show(elliptic_f(x,x))
\newcommand{\Bold}[1]{\mathbf{#1}}F(x\,|\,x)
```
While the changes to `_print_latex_` were made on the 15046 branch two years ago the branch itself was merged into develop only 5 weeks ago.

**Comment by paulmasson** [comment]
Doh! Wasn't much involved with that ticket. A bit odd for two-year old code to appear rather suddenly like that, but I guess that's Sage.

Looking forward to the upgrade...

**Comment by paulmasson** [comment]
Andrey, why the Sage upgrade before 7.3 is out?

**Comment by novoselt** [comment]
To get new JSmol in which happened to be based on 7.3.beta9. Not sure if it will hit 7.3 at all, but I hope so.
