### ISSUE TITLE
Accessing SageMathCell as a web API

### ISSUE THREAD

**Issue by paulmasson** [sagemath/sagecell#469]
Inspired by this [ask question](http://ask.sagemath.org/question/34443/show-sage-results-in-a-webpage-as-string-not-as-sagecell-box/), would it be possible to access the results of SageMathCell as a JSON string? This would of course only apply to calculations whose results can be returned in JSON format.

For example, evaluating `P=Primes(); print P.next(2016)` in the cell returns the answer in a `<pre>` tag with the class `sagecell_stdout`. Could outputs with this class name optionally be returned by the server as JSON?

**Comment by novoselt** [comment]
This may be it: https://github.com/sagemath/sagecell/wiki/Messages#blocking-web-service

**Comment by paulmasson** [comment]
Thanks for the info! Hadn't seen this page before.

Finally got the service to work at the command line and using XMLHttpRequest, which was a fun diversion. I've updated my answer at ask.sagemath.org, but I'll also add a bunch of that to the documention here since there are some big gaps.

**Comment by paulmasson** [comment]
@novoselt the documentation for this service is in the wiki, which is not open to me for editing. Since there doesn't appear to be a way to create pull requests against a wiki on Github, how do you want to handle updates? Create documents in the code repository or something else?

**Comment by paulmasson** [comment]
@novoselt I've created a short page on my website with the basics of using the web service:

 [Accessing SageMath as a Web Service](http://analyticphysics.com/Mathematical Methods/Accessing SageMath as a Web Service.htm)

Feel free to copy what you want to this wiki. There's a link at the bottom to an example application that downloads data from the server to visualize real and imaginary parts of special functions with Three.js.

**Comment by novoselt** [comment]
I actually don't want to copy anything to the wiki and would very much prefer to have all documentation in the same repository as the code as it is already the case with embedding instructions. What are advantages of this wiki??? If you are willing to do the move I'll be happy to merge pull requests ;-)

**Comment by paulmasson** [comment]
Moving documentation from wiki commenced
