### ISSUE TITLE
br in .salvus-3d-viewer causes blank line

### ISSUE THREAD

**Issue by davidfarmer** [sagemath/sagecell#471]
Line 50 in the file
js/cell_body.html
is just a  < br >

This causes a blank line on the web page, which I can't easily remove with CSS.

Can it just be deleted?

**Comment by novoselt** [comment]
Solved by 8d3ad1ec35441609dc988d686b840a427cc2cb46 thanks for suggestion!

**Comment by davidfarmer** [comment]
Thanks!  That fixed my layout problem.

-David
