### ISSUE TITLE
ERROR    Distro 'ubuntu16.04' does not exist in our dictionary

### ISSUE THREAD

**Issue by heiderich** [sagemath/sagecell#480]
Trying to build the VM on Debian Jessie I obtain the following error:

ERROR    Distro 'ubuntu16.04' does not exist in our dictionary

In fact, ubuntu16.04 is not in the list of supported os-variants (at least not on Debian Jessie). Maybe there could be an alternative way of installation, for instance by specifying a previously downloaded ISO image. I am not sure whether one can easily configure additional os-variants for virt-install.

**Comment by novoselt** [comment]
I encounter such problems as well during OS switches, but you can try some other name as mentioned in the documentation steps:

"If your virt-install does not understand OSVARIANT=ubuntuxenial, you may try a different version of Ubuntu here, while keeping the same LOCATION, virt-install --os-variant list may be useful. Using a different base OS is probably possible, but will likely require further changes to build commands."

If you know of a better way to handle this issue, please let us know!
