### ISSUE TITLE
Add sage-py3 to the list of languages

### ISSUE THREAD

**Issue by slel** [sagemath/sagecell#516]
It would be nice to add "sage-py3" to the list of languages, which
currently has: sage, GAP, GP, HTML, Maxima, Octave, Python, R, Singular.
This would run a Python3-based version of SageMath.

**Comment by novoselt** [comment]
It could be nice, but this will require considerable work to redesign how kernels are handled and there is little point in supporting Python2 beyond the end of this year. So either this summer, if Sage is ready, or in the end of the year, when Sage has to be ready, SageMathCell will switch to Python3 completely.
