### ISSUE TITLE
embedded_sagecell.js overwrites an existing copy of jQuery in the page

### ISSUE THREAD

**Issue by christianp** [sagemath/sagecell#521]
The file `embedded_sagecell.js` seems to load a copy of jQuery which resets `window.jQuery` and `window.$`, regardless of whether they're already defined. This caused me some problems because I've already loaded some jQuery extensions before sage cell loads.

Ideally, sage cell should keep its copy of jQuery in local scope. If that's not possible, it should at least check if `jQuery` is already defined, and not load the new copy if it is.

**Comment by novoselt** [comment]
jQuery is loaded via require.js, so theoretically it should not interfere with your own copy. Glancing at the code I can't see why it escapes to global namespace, unless that's just how jQuery behaves.

**Comment by christianp** [comment]
The [require.js docs](https://requirejs.org/docs/jquery.html) say that jQuery always sets the globals.

The [jQuery docs](https://api.jquery.com/jQuery.noConflict/) say you should call `$.noConflict( true )`. 

If I can get sagecell to build, I'll submit a pull request that does this.

**Comment by novoselt** [comment]
Shouldn't happen anymore after 0b4ed5f014ee15c7624e47f8c82f515cd3733b96

**Comment by christianp** [comment]
Thanks! Sorry I didn't get round to doing this properly myself.

**Comment by novoselt** [comment]
Has it actually fixed or at least improved your problem?

**Comment by christianp** [comment]
I'm on paternity leave so won't be in a position to check for a while, but from the commit I think it would.

**Comment by novoselt** [comment]
That is awesome, enjoy this time, it does not last long ;-)
