### ISSUE TITLE
Accessing sagecellInfo object

### ISSUE THREAD

**Issue by ro70** [sagemath/sagecell#543]
Why do I see a `sagecellInfo` content but having no access to it?

```
var sagecellInfo = sagecell.makeSagecell({
          inputLocation: '#' + sagecellId,
          evalButtonText: 'go',
          code: code,
});

console.log(sagecellInfo)
console.log(sagecellInfo.code)  // <== undefined
```

<img width="452" alt="grafik" src="https://user-images.githubusercontent.com/17289564/124228442-8147f800-db0c-11eb-8a43-e80d6309f9cc.png">

EDIT: Seems to be an async thing. I'm calling the `sagecellInfo.code` too early. I could set a `callback` function in `makeSagecell`. But how can I access the `sagecellInfo` just created from there?

**Comment by novoselt** [comment]
Indeed it is because of asynchronous calls. I imagine that if you create a variable to make it available inside your call back function and then call makeSagecell with a callback argument, you will have access to it.
