### ISSUE TITLE
Wrong indentation in first line for Macaulay2 output

### ISSUE THREAD

**Issue by nielsthl** [sagemath/sagecell#545]
Is there an easy fix for adjusting the (missing) indentation of the line of exponents below?

![sageM2formaterr](https://user-images.githubusercontent.com/23010769/149794880-de044d1b-1b11-47c4-bda9-390d372248c5.png)

It seems to work after the first line:

![sageM2ok](https://user-images.githubusercontent.com/23010769/149794934-ed6285a8-2818-47be-9d03-9d00dc74cac3.png)

**Comment by novoselt** [comment]
Should be solved by e250ef4467ce5447912fba3e8a7f3e4a9a360ed2
