### ISSUE TITLE
makeSagecell fails to return cellInfo object

### ISSUE THREAD

**Issue by rayellis4** [sagemath/sagecell#555]
The makeSagecell call in the following snippet returns "undefined" and completes asynchronously:

<html>
    <head>
        <script src="https://sagecell.sagemath.org/static/embedded_sagecell.js"></script>
        <script>
         const info = window.sagecell.makeSagecell({
             inputLocation: "#mycell"
         })
         alert(info)
        </script>
    </head>
    <body>
        <div id="mycell"></div>
    </body>
</html>

**Comment by siefkenj** [comment]
Can you let me know what you're using `cellInfo` for? Making the cell is fundamentally asynchronous (the old code was asynchronous too, but in a very awkward way, so I'm guessing your use case either ran the `makeSagecell` code later in the page load or it didn't use all the info in `cellInfo`...)

**Comment by rayellis4** [comment]
Whatever changes that have been made since I posted (1500 lines or so of new embedded_sagecell.js!!) seem to have fixed the problem, so this all might be moot. But, to answer to you:
The cellInfo was used as an argument to deleteSagecell later in the program, which couldn't occur programmatically until the callback function executed.
The cell was deleted when the user finished with example at hand. The cell is created in an iFrame, btw, to work around the jquery version problem.
You can see the page on github. It's just a web page, no backend, and it should load reasonably quickly even on your first visit. Here's [an example](https://rayellis4.github.io/group-explorer/GroupInfo.html?groupURL=groups/Q_4.group). About halfway down the page is a section entitled "Computed Properties", and each of the subsections (e.g., Abelian group, Class equation) has a "Compute this in GAP" button that demonstrates the GAP computation using sagecell. The first execution upon visiting the page works properly, but subsequent runs (used to) fail because the deleteSagecell call had an undefined cellInfo argument. 
Thanks for fixing this so quickly, I'll bet you have bigger projects to work on than a minor bug. 
And thanks for sharing sagecell!

  -- Ray

**Comment by novoselt** [comment]
Ray - the issue was fixed in #556 and was not a drastic change. A "quick fix" was reverting to an older version of JavaScript, that differed quite a bit from the current state. The changes, however, should not break existing pages, so you have reported a valid bug. Please check that it is fixed now - as far as I can see with a test case and link that you have provided, it is indeed.

**Comment by rayellis4** [comment]
Andrey --

Yes, it is fixed.  Thank you!

   -- Ray
