### ISSUE TITLE
SageCell on Octave language displays gnuplot warning

### ISSUE THREAD

**Issue by bkpark** [sagemath/sagecell#566]
Running any command on SageCell with Octave language displays the gnuplot warning shown below. Running Octave command with octave("...") syntax seems not to trigger this. Is there a way to suppress the warning (... or as the error message says, using QT toolkit)?
![image](https://user-images.githubusercontent.com/12738819/199108929-994d1390-69ac-4b87-b7ee-24b9b4dc1702.png)

**Comment by novoselt** [comment]
I got a report about this problem and didn't figure out yet how to fix it. There is extra octave code added to the user one to make plots work in SageMathCell. We don't support any interaction, just saving and displaying a file, and gnuplot probably will continue to work fine for that, but the message indeed has to go away.

**Comment by novoselt** [comment]
Should be fixed by 9da63e0141229dd47a34d76eb3f5c128c75616a3
