### ISSUE TITLE
Calculus Error

### ISSUE THREAD

**Issue by owenbiesel** [sagemath/sagecell#578]
The symbolic calculator seems to be making a mistake while simplifying integrals: the integral

`integral(sqrt(x^2+x^4),x,-2,2)`

returns 0, even though the function is nonnegative, and positive away from x = 0. I suspect it is attempting to rewrite the integrand as x * sqrt(1 + x^2), which is an odd function with integral 0, whereas it should rewrite the integrand as abs(x) * sqrt(1+x^2). The numerical integrator correctly returns a value for the integral of about 6.79.

**Comment by novoselt** [comment]
That has nothing to do with SageMathCell however, which is just sending the code to SageMath! It seems to me that similar issues are popping up regularly over the years and they are due to bugs in the underlying software (most likely not even SageMath).

**Comment by roed314** [comment]
I would suggest browsing the issues [here](https://github.com/sagemath/sage/issues) to see if you can find one that already addresses this problem, and creating one if you can't.
